### ISSUE TITLE
训练自己的ELMo时报错

### ISSUE THREAD

**Issue by KevinChen1994** [HIT-SCIR/ELMoForManyLangs#20]
你好，我的开发环境为Python3.6。我使用的是最新的版本，训练数据是一个txt文件，一共有13万行，每一行是一条语句，每条语句通过空格分词。配置文件使用的是cnn_50_100_512_4096_sample.json。训练过程中，在classify_layer.py的113行报错。错误信息如下：
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/chenmeng/PycharmProjects/ELMoForManyLangs-master/elmoformanylangs/biLM.py", line 696, in <module>
    train()
  File "/Users/chenmeng/PycharmProjects/ELMoForManyLangs-master/elmoformanylangs/biLM.py", line 613, in train
    train, valid, test, best_train, best_valid, test_result)
  File "/Users/chenmeng/PycharmProjects/ELMoForManyLangs-master/elmoformanylangs/biLM.py", line 340, in train_model
    loss_forward, loss_backward = model.forward(w, c, masks)
  File "/Users/chenmeng/PycharmProjects/ELMoForManyLangs-master/elmoformanylangs/biLM.py", line 241, in forward
    self.classify_layer.update_negative_samples(word_inp, chars_inp, mask_package[0])
  File "/Users/chenmeng/PycharmProjects/ELMoForManyLangs-master/elmoformanylangs/modules/classify_layer.py", line 113, in update_negative_samples
    word = word_inp[i][j].tolist()
AttributeError: 'int' object has no attribute 'tolist'

谢谢能抽时间回答我的问题！

**Comment by Oneplus** [comment]
问题是出现在训练开始还是训练了一段时间后出错呢？

如果您能提供一个几百句的数据样本，我们可能能把你复现错误。

**Comment by KevinChen1994** [comment]
是在刚开始训练的时候报错的。这是我的300条训练数据，您可以下载下来复现一下这个错误。https://pan.baidu.com/s/1-CGg-y6W5UZ1JNcoGBeh-Q
感谢！

**Comment by KevinChen1994** [comment]
问题解决了，是pytorch版本的问题。感谢！

**Comment by tsungruihon** [comment]
@KevinChen1994 您好 我想问下 我的训练数据有6w多 但是实际的训练实例只有9千多。想请教下您有发现类似的情况吗
```
2019-01-28 14:18:15,426 INFO: training instance: 9376, training tokens: 459418.
2019-01-28 14:18:15,489 INFO: Truncated word count: 0.
2019-01-28 14:18:15,489 INFO: Original vocabulary size: 14878.
2019-01-28 14:18:15,623 INFO: Word embedding size: 14880
2019-01-28 14:18:15,851 INFO: Char embedding size: 3292
```
