### ISSUE TITLE
Problem for using pre-trained representations and possible solutions

### ISSUE THREAD

**Issue by rivershadowy** [HIT-SCIR/ELMoForManyLangs#3]
Hi,

I followed the instructions as given and had the hdf5 encoded dict dumped onto the disk. Everything worked well until I load the model using AllenNLP ELMo, as  in the code presented in here: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md

`from allennlp.modules.elmo import Elmo, batch_to_ids
options_file = "path/to/my/option/json"
weight_file = "path/to/the/pretrained/hdf5/in/last/step"
elmo = Elmo(options_file, weight_file, 2, dropout=0)
sentences = [['First', 'sentence', '.'], ['Another', '.']]
character_ids = batch_to_ids(sentences)
embeddings = elmo(character_ids)`

My options file is:

`{"lstm": {"use_skip_connections": true, "projection_dim": 512, "cell_clip": 3, "proj_clip": 3, "dim": 4096, "n_layers": 2}, "char_cnn": {"activation": "relu", "filters": [[1, 32], [2, 32], [3, 64], [4, 128], [5, 256], [6, 512], [7, 1024]], "n_highway": 2, "embedding": {"dim": 16}, "n_characters": 262, "max_characters_per_token": 50}}`

which is the same as in the original paper (Not very sure, please let me know if I made a mistake), because 

> We use the same hyperparameter settings as Peters et al. (2018) for the biLM and the character CNN

However, when I exert this script,  the following error shows up:

`Traceback (most recent call last):
  File "output_elmo_vec.py", line 15, in <module>
    elmo = Elmo(options_file, weight_file, 2, dropout=0)
  File "/user01/data/anaconda2/envs/allennlpenv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 99, in __init__
    vocab_to_cache=vocab_to_cache)
  File "/user01/data/anaconda2/envs/allennlpenv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 499, in __init__
    self._token_embedder = _ElmoCharacterEncoder(options_file, weight_file, requires_grad=requires_grad)
  File "/user01/data/anaconda2/envs/allennlpenv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 285, in __init__
    self._load_weights()
  File "/user01/data/anaconda2/envs/allennlpenv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 373, in _load_weights
    self._load_char_embedding()
  File "/user01/data/anaconda2/envs/allennlpenv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 380, in _load_char_embedding
    char_embed_weights = fin['char_embed'][...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/user01/data/anaconda2/envs/allennlpenv/lib/python3.6/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'char_embed' doesn't exist)"`

I searched on Google and found this particular error of  'char_embed doesn't exist', was actually caused by customized BiLM training:
https://github.com/allenai/allennlp/issues/1521#issuecomment-407476528

According to this post, it seems AllenNLP will not officially offer support for customized pre-trained models without 'char_cnn' params.  May I suggest keeping this parameter during training, so that the pretrained model has this part? 

Thank you very much for your reply. ;)

**Comment by Oneplus** [comment]
Sorry for late reply.

By
> We use the same hyperparameter settings as Peters et al. (2018) for the biLM and the character CNN

We mean we use the same number of hidden units and other stuff.

To my understanding, our release is not directly portable to AllenNLP because we support unicode characters. This leads to difference in model architecture. We have a char_emb layer of *variable length* to convert unicode character to embeddings, while they use a fix-sized char embedding layer .

Unfortunately, we don't have a good solution to make our release works with AllenNLP by now. Any suggestion will be welcome.

**Comment by Oneplus** [comment]
Since issue #1 has the same concern, I will close this one and redirect all the discussion to #1
